sdf_contact_estimation/sdf_map/sdf_file_path: $(find whole_body_planning_data)/sdf/gazebo/gazebo_oc_pallet_terrain2.esdf
checkpoints:
  - p1: [0, 0.0]
    p2: [1.0, 0.0]
  - p1: [8.0, 0]
    p2: [8, 0]
