sdf_contact_estimation/sdf_map/sdf_file_path: $(find whole_body_planning_data)/sdf/gazebo/gazebo_oc_pallet_terrain2.esdf
checkpoints:
  - p1: [1, 1]
    p2: [1, -1]
  #- p1: [3, 1]
    #p2: [3, -1]
  - p1: [7.5, 1]
    p2: [7.5, -1]
